<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>TiaoKe</AssemblyName>
    <RootNamespace>TiaoKe.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\tiaoke.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Assets\tiaoke-icon.png" />
    <None Remove="Assets\tiaoke.ico" />
    <Resource Include="Assets\tiaoke-icon.png" />
    <Resource Include="Assets\tiaoke.ico" />
  </ItemGroup>
</Project>
